apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-dy7o
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lxoo-tenant/rhtap-demo-app/hacbs-test-project-dy7o@sha256:bb33d24416b7249cfa5da63974672163e48ecc04fa57563a3459370214a35729
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
